"""Bounded beam-search tactic engine (SPEC 3.11).

heapq elements are ``(priority, length_tiebreak, monotonic_counter, depth,
fingerprint, proof)`` so ties never reach non-comparable payloads (v39 P1-10
TypeError fix). ``length_tiebreak`` is the BFS-Prover length-normalization
penalty ``alpha * log(L)`` (L = accumulated proof length in tokens;
arXiv:2502.03438, frontier_atp Top-8 #3); with ``alpha = 0`` it is 0 for
every node and the monotonic counter reproduces the old FIFO tie-break
exactly.
Candidate tactics are generated by the PROVER and EXPLORER roles split by
``strategy.explorer_share`` (temperatures 0.2 / 0.5 for diversity), and every
candidate full-proof state passes through the unified verifier.
"""

from __future__ import annotations

import hashlib
import heapq
import itertools
import logging
import math
import time
from typing import Optional

from v40_sorry_resolver.models import ProofStatus, ResolutionResult, SorryTask
from v40_sorry_resolver.llm.router import Role
from v40_sorry_resolver.engine import extract_lean_code

logger = logging.getLogger("v40.tactic_search")

# Safety multiplier bounding total node expansions.
_EXPANSION_BUDGET_FACTOR = 4
#: Default length-normalization weight (config ``search_length_norm_alpha``).
DEFAULT_LENGTH_NORM_ALPHA = 0.1


class TacticSearchEngine:
    def __init__(self, router, verifier, metrics=None, length_norm_alpha=None):
        self.router = router
        self.verifier = verifier
        self.metrics = metrics
        if length_norm_alpha is None:
            length_norm_alpha = DEFAULT_LENGTH_NORM_ALPHA
        self._length_norm_alpha = max(0.0, float(length_norm_alpha))

    def _length_tiebreak(self, proof: str) -> float:
        """``alpha * log(L)`` penalty; L = accumulated proof tokens (>=1)."""
        if self._length_norm_alpha <= 0.0:
            return 0.0
        tokens = len(proof.split())
        return self._length_norm_alpha * math.log(max(tokens, 1))

    async def search(self, task: SorryTask, strategy) -> ResolutionResult:
        t0 = time.monotonic()
        max_depth = max(1, int(strategy.tactic_search_depth))
        width = max(1, int(strategy.tactic_search_width))
        share = min(max(float(getattr(strategy, "explorer_share", 0.3)), 0.0), 1.0)

        prover = self.router.client(Role.PROVER)
        explorer = self.router.client(Role.EXPLORER) if share > 0 else prover

        tokens_used = 0
        nodes_expanded = 0
        visited: set[str] = set()
        counter = itertools.count()  # monotonic; fixes heapq tie TypeError
        max_expansions = max_depth * width * _EXPANSION_BUDGET_FACTOR

        # Beam holds (proof_state, depth); root is the empty proof.
        beam: list[tuple[str, int]] = [("", 0)]
        best_remaining: Optional[int] = None

        for depth in range(1, max_depth + 1):
            # (priority, length_tiebreak, counter, depth, fingerprint, proof)
            candidates: list[tuple[float, float, int, int, str, str]] = []
            for state, _ in beam:
                if nodes_expanded >= max_expansions:
                    break
                tactics, toks = await self._propose_next(
                    task, state, prover, explorer, width, share
                )
                tokens_used += toks
                for tactic in tactics:
                    new_state = f"{state}\n{tactic}".strip() if state else tactic
                    fingerprint = hashlib.sha1(new_state.encode("utf-8")).hexdigest()
                    if fingerprint in visited:
                        continue
                    visited.add(fingerprint)
                    nodes_expanded += 1
                    try:
                        vr = await self.verifier.verify_proof(task, new_state)
                    except Exception as exc:
                        logger.debug("search verify error: %s", exc)
                        continue
                    if getattr(vr, "ok", False):
                        return ResolutionResult(
                            task_id=task.id,
                            success=True,
                            status=ProofStatus.SOLVED_SEARCH,
                            proof=new_state,
                            solver="tactic_search",
                            iterations=nodes_expanded,
                            tokens_used=tokens_used,
                            time_elapsed=time.monotonic() - t0,
                            remaining_goals=0,
                            verification_passed=True,
                        )
                    rem = getattr(vr, "remaining_sorries", -1)
                    if isinstance(rem, int) and rem >= 0:
                        best_remaining = (
                            rem
                            if best_remaining is None
                            else min(best_remaining, rem)
                        )
                        priority = float(rem) + depth * 0.1
                    else:
                        priority = 50.0 + depth * 0.1
                    heapq.heappush(
                        candidates,
                        (
                            priority,
                            self._length_tiebreak(new_state),
                            next(counter),
                            depth,
                            fingerprint,
                            new_state,
                        ),
                    )
            if not candidates:
                break
            beam = [
                (entry[5], entry[3])
                for entry in heapq.nsmallest(width, candidates)
            ]

        return ResolutionResult(
            task_id=task.id,
            success=False,
            status=ProofStatus.FAILED_ALL,
            solver="tactic_search",
            iterations=nodes_expanded,
            tokens_used=tokens_used,
            time_elapsed=time.monotonic() - t0,
            remaining_goals=best_remaining if best_remaining is not None else -1,
            verification_passed=False,
            error="search exhausted",
        )

    async def _propose_next(
        self,
        task: SorryTask,
        state: str,
        prover,
        explorer,
        width: int,
        share: float,
    ) -> tuple[list[str], int]:
        """Generate up to ``width`` next-tactic candidates, split by role."""
        n_explorer = int(round(width * share)) if explorer is not prover else 0
        n_prover = max(1, width - n_explorer)
        if explorer is prover:
            n_explorer = 0
        plan = [(prover, 0.2)] * n_prover + [(explorer, 0.5)] * n_explorer

        current = state if state else "(empty - propose the first tactic)"
        prompt = (
            f"Theorem {task.theorem_name}.\n"
            f"Goal: {task.goal_state or '(infer from context)'}\n"
            f"Current partial proof:\n{current}\n"
            "Propose the NEXT single Lean 4 tactic line that makes progress. "
            "Reply with ONE tactic line only, no explanation."
        )
        system = "You are a Lean 4 tactic proposer. One tactic line per reply."

        tactics: list[str] = []
        tokens = 0
        for client, temperature in plan:
            try:
                resp = await client.generate(
                    prompt,
                    system_prompt=system,
                    temperature=temperature,
                    max_tokens=128,
                    cache_key=None,
                )
            except Exception as exc:
                logger.debug("tactic proposal failed: %s", exc)
                continue
            if getattr(resp, "error", None):
                continue
            tokens += int(getattr(resp, "prompt_tokens", 0) or 0) + int(
                getattr(resp, "completion_tokens", 0) or 0
            )
            line = self._first_tactic_line(getattr(resp, "text", "") or "")
            if line:
                tactics.append(line)
        return tactics, tokens

    @staticmethod
    def _first_tactic_line(text: str) -> str:
        extracted = extract_lean_code(text)
        for raw in extracted.splitlines():
            line = raw.strip()
            if not line or line.startswith("--") or line.startswith("#"):
                continue
            if line.startswith("by"):
                line = line[2:].strip()
                if not line:
                    continue
            return line
        return ""
